// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`

  GET_NOTIFICATIONS_REQUEST
  GET_NOTIFICATIONS_SUCCESS
  GET_NOTIFICATIONS_FAILURE

  UPDATE_NOTIFICATIONS_REQUEST
  UPDATE_NOTIFICATIONS_SUCCESS
  UPDATE_NOTIFICATIONS_FAILURE
  
`)
